services:
  mongodb-service:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: zecodeuser
      MONGO_INITDB_ROOT_PASSWORD: zecodepassword
    volumes:
      - mongo-data:/data/db

  ze-code-challenge-service:
    container_name: ze-code-challenge-application
    build: ../.
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-service
    environment:
      MONGODB_URI: mongodb://zecodeuser:zecodepassword@mongodb-service:27017/collection-ze-challenge?authSource=admin


volumes:
  mongo-data: